version: '3.3'

services:
  web:
    build: .
    container_name: cryptoinsights_web
    expose:
      - "5000"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: production

  nginx:
    image: nginx:latest
    container_name: cryptoinsights_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
